Feat/dca
Pacoca-io/contracts pull request #3
Opened 2022-08-18 14:03 UTC by AmendoBobo404

2022-08-18 14:56 UTC, MrPeanutz requested changes

2023-08-10 18:45 UTC, MrPeanutz requested changes

2023-08-10 18:45 UTC, MrPeanutz commented on PeanutDCA.sol
> +            uint[] memory amountsOut = IPancakeRouter02(pool.router).swapExactTokensForTokens(
1. get current output token balance
2. use method that supports tokens with transfer fee
3. get outputToken balance delta to know the output amount

2023-08-10 18:45 UTC, MrPeanutz commented on PeanutDCA.sol
> +            accruedSwapQuoteByPool[poolId][pool.performedSwaps + 1] = accruedSwapQuoteByPool[poolId][pool.performedSwaps] + swapQuote;
try

`mapping(uint16 => uint) storage accuedPoolSwapQuote = accruedSwapQuoteByPool[poolId]`

2023-08-10 18:45 UTC, MrPeanutz commented on PeanutDCA.sol
> +            uint swapQuote = _calculateSwapQuote(pool.nextSwapAmount, outputTokenAmount);
`uint swapQuote = _outputTokenAmount * SWAP_QUOTE_PRECISION / _inputTokenAmount`

2023-08-10 18:45 UTC, MrPeanutz commented on PeanutDCA.sol
> +                pool.nextSwapAmount,
assign to inputTokenAmount for use in the event

2023-08-10 18:45 UTC, MrPeanutz commented on PeanutDCA.sol
> +            emit Swap(poolId, pool.nextSwapAmount, outputTokenAmount, fee);
use `inputTokenAmount` instead of `pool.nextSwapAmount`

2023-08-10 18:45 UTC, MrPeanutz commented on PeanutDCA.sol
> +        if (userPostions.length == 0 || _positionId >= userPostions.length)
you can use `if (_positionId >= userPostions.length)`

2023-08-10 18:45 UTC, MrPeanutz commented on PeanutDCA.sol
> +        uint inputTokenAmount = _calculateInputTokenBalance(msg.sender, position.poolId, _positionId);
`uint inputTokenAmount = (position.finalSwap - poolInfo[_poolId].performedSwaps) * position.swapRate`

2023-08-10 18:45 UTC, MrPeanutz commented on PeanutDCA.sol
> +        if (_path.length < 2)
greater or equal 2

2023-08-10 18:45 UTC, MrPeanutz commented on PeanutDCA.sol
> +    function setPoolPath(uint _poolId, address[] memory _path) external onlyOwner {
add set router

2023-08-10 18:45 UTC, MrPeanutz commented on PeanutDCA.sol
> +    mapping(address => PositionInfo[]) public positionInfo;
positionInfo should be internal

2023-08-10 18:45 UTC, MrPeanutz commented on PeanutDCA.sol
> +    }
remove this function

2023-08-10 18:45 UTC, MrPeanutz commented on PeanutDCA.sol
> +        swappedWithFee = swapped - _calculateFee(swapped);
return instead

2023-08-10 18:45 UTC, MrPeanutz commented on PeanutDCA.sol
> +    function _calculateOutputTokenBalance(address _user, uint _poolId, uint _positionId) internal view returns (uint swappedWithFee) {
no need for named return

2023-08-10 18:45 UTC, MrPeanutz commented on PeanutDCA.sol
> +    function _calculateOutputTokenBalance(address _user, uint _poolId, uint _positionId) internal view returns (uint swappedWithFee) {
if you want you can add a soldoc mentioning the fee is subtracted

2023-08-14 16:59 UTC, AmendoBobo404 commented on PeanutDCA.sol
> +                firstSwap: pool.performedSwaps,
This variable wasn't being used at for practical purposes, only to emit the create position event. Also took a quick look at the front-end branch of the DCA and isn't being used either, so I decided to remove it from the contract.

2023-08-14 18:40 UTC, AmendoBobo404 commented on PeanutDCA.sol
> +            uint swapQuote = _calculateSwapQuote(pool.nextSwapAmount, outputTokenAmount);
I've tried this approach, but the problem is that we don't have a local variable called `_inputTokenAmount` neither `outputTokenAmount`. The code will look something like this

```sol
uint swapQuote = outputTokenDelta * SWAP_QUOTE_PRECISION / pool.nextSwapAmount
```

Even though the name of the variable indicates what this formula is calculating, it isn't very semantic as 
```sol
_outputTokenAmount * SWAP_QUOTE_PRECISION / _inputTokenAmount
```

Also calling this function inline instead of attributing it to a variable is also a no go, as the line below is already really big, and the readability would become worst that already is

IMO this redundancy plays a significant part in understanding the whole function, and I believe we can leave this line as is. A call to a `pure` function + a variable allocation is really cheap.

2023-08-14 20:15 UTC, AmendoBobo404 commented on PeanutDCA.sol
> +    }
as mentioned in the comment above, this function needs to stay

2023-08-21 17:08 UTC, MrPeanutz requested changes

2023-08-21 17:08 UTC, MrPeanutz commented on PeanutDCA.sol
> +
add `setPoolRouterAndPath` function

2023-08-21 17:08 UTC, MrPeanutz commented on PeanutDCA.sol
> +    function balanceOf(address _token) public view returns (uint balance) {
tokenBalance makes more sense, balance of seems like its the balance of a user

2023-08-21 18:19 UTC, MrPeanutz approved these changes

2023-08-21 18:20 UTC, merged